### ISSUE TITLE
how to use the releases for msys2?

### ISSUE THREAD

**Issue by HaidStefan** [kekyo/gcc-toolchain#5]
Hi,

How can I add the releases to my already existing MSYS2 system?

many thanks
cheers
stefan

**Comment by kekyo** [comment]
@HaidStefan Hello!

Did you try install mingw toolchains by pacman?

See README.md's "Build" section:

```
pacman -Syuu
pacman -S bzip2 base-devel mingw-w64-x86_64-toolchain
```

These fragments install the base toolchain sets without breaking your environment (maybe :)
Or did you have any troubles?

**Comment by HaidStefan** [comment]
@kekyo No, this worked successfully, but after that I tried to build the toolchain with `build.sh arm-none-eabi` and that did not work. I get a lot of errors there.
After that I tried to install a release made from you. I use the MINGW64 Shell with the blue icon. But there I got that error:
```
$ pacman -U gcc-7.2.0_x86_64-w64-mingw32_arm-none-eabi_2018-01-16.tar.bz2
Lade Pakete...
Error: Missing Packet-Metadata in gcc-7.2.0_x86_64-w64-mingw32_arm-none-eabi_2018-01-16.tar.bz2
Fehler: 'gcc-7.2.0_x86_64-w64-mingw32_arm-none-eabi_2018-01-16.tar.bz2': wrong or corrupted package

```
Do you have any Idea?
Should I also post the build error from the build.sh script?

**Comment by kekyo** [comment]
@HaidStefan the answer for two parts:

* I'm trying build with latest version for MSYS2 ( http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20180531.exe ), please wait ;)
* gcc-7.2.0_x86_64-w64-mingw32_arm-none-eabi_2018-01-16.tar.bz2 is not pacman style package. It's plain tar-gz archive. You can extract and place to your folder. It means portable-style.

**Comment by kekyo** [comment]
@HaidStefan sorry later. I tested current MSYS2 environment and just cause problem too.
I'm thinking about MSYS2 default gcc package (current version) may causes unknown problem...
I feel use gcc's multi-staging buid steps (with fixed version) to fix problem, we have to change build.sh scripts.

**Comment by HaidStefan** [comment]
Thanks a lot for trying, i found an other solution for building micropython now (See: https://github.com/micropython/micropython/issues/3941)
